# generated by the polygon register: one ctest case per open problem,
# green while the problem reproduces (see docs/POLYGON.md)
add_polygon_case(P-1)
add_polygon_case(P-2)
add_polygon_case(P-3)
add_polygon_case(P-4)
